name = "Clientele"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "896b6654a608afd49eaa770b2a5679bb64aedb0493b332adbde3aee7c2d45178"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
